import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/yaQVpEFfD6ASpm0Pii5DXY/Labcorp-Bootstrap-v4?node-id=130-8098",
  {
    props: {
      label: figma.boolean("Label"),
      text: figma.string("Text"),
      showLeftIcon: figma.boolean("Show Left Icon"),
      leftIcon: figma.instance("Left Icon"),
      showRightIcon: figma.boolean("Show Right Icon"),
      rightIcon: figma.instance("Right Icon"),
      dropdown: figma.boolean("Dropdown"),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
        Large: "large",
      }),
      type: figma.enum("Type", {
        Primary: "primary",
        Secondary: "secondary",
        Link: "link",
        "Alt Primary": "alt-primary",
        "Alt Secondary": "alt-secondary",
        Success: "success",
        "Success Outline": "success-outline",
        Danger: "danger",
        "Danger Outline": "danger-outline",
        Info: "info",
        "Info Outline": "info-outline",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Active: "active",
        Disabled: "disabled",
      }),
    },
    example: (props) => html`<button />`,
  },
)
