import figma, { html } from '@figma/code-connect/html';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect('<FIGMA_BUTTONS_BUTTONS>', {
  props: {
    label: figma.boolean('Label'),
    text: figma.string('Text'),
    showLeftIcon: figma.boolean('Show Left Icon'),
    leftIcon: figma.instance('Left Icon'),
    showRightIcon: figma.boolean('Show Right Icon'),
    rightIcon: figma.instance('Right Icon'),
    dropdown: figma.boolean('Dropdown'),
    size: figma.enum('Size', {
      Default: 'md',
      Small: 'sm',
      Large: 'lg',
    }),
    variant: figma.enum('Variant', {
      Primary: 'primary',
      Secondary: 'secondary',
      Link: 'link',
      'Alt Primary': 'alt-primary',
      'Alt Secondary': 'alt-secondary',
      Success: 'success',
      'Success Outline': 'success-outline',
      Danger: 'danger',
      'Danger Outline': 'danger-outline',
      Info: 'info',
      'Info Outline': 'info-outline',
    }),
    state: figma.enum('State', {
      Default: 'default',
      Hover: 'hover',
      Active: 'active',
      Disabled: 'disabled',
    }),
  },
  example: ({ state, text, variant, size }) => html`<bs-button
    label=${text}
    type="button"
    variant=${variant}
    state=${state}
    size=${size}
  ></bs-button>`,
});
