import figma, { html } from '@figma/code-connect/html';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect('<FIGMA_ICONS_ICONS>', {
  props: {
    name: figma.enum('Name', {
      '3d Rotation': '3d-rotation',
      Accessibility: 'accessibility',
      Accessible: 'accessible',
      'Accessible Forward': 'accessible-forward',
      'Account Box': 'account-box',
      'Account Child': 'account-child',
      'Account Child Invert': 'account-child-invert',
      'Account Circle': 'account-circle',
      'Accessibility New': 'accessibility-new',
    }),
  },
  example: (props) => html`<icon name=${props.name} />`,
});
