import figma, { html } from '@figma/code-connect/html';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect('<FIGMA_BUTTONS_BUTTONS>', {
  props: {
    label: figma.string('Label'),
    rank: figma.enum('Rank', {
      Primary: 'primary',
      Secondary: 'secondary',
      Success: 'success',
      Danger: 'danger',
      Warning: 'warning',
      Info: 'info',
      Light: 'light',
      Dark: 'dark',
      Link: 'link',
    }),
    size: figma.enum('Size', {
      Default: 'default',
      Small: 'small',
      Large: 'large',
    }),
  },
  example: (props) => html`<bs-button
    label=${props.label}
    type="button"
    rank=${props.rank}
    size=${props.size}
  ></bs-button>`,
});
